import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '@/models/Chat'; // Importujemy model Chat
import '@/models/User'; // Jeśli używasz modelu User
import '@/models/UserChats'; // Importujemy model UserChats
import "./globals.css";
import Image from "next/image";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "COSMIC AI",
  description: "Generated by create next app",
  icons:{
    icon: "/rocket.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>   
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header></header>
        {children}
      </body>
    </html>
  );
}
